version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd client
      - npm install -g yarn
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - aws s3 cp --recursive ./dist s3://feve-deploy-s3-buckets/

artifacts:
  files:
    - 'server/*'
    - 'appspec.yml'
